language: cpp
sudo: required
os: linux
compiler: gcc
# dist: xenial  # bionic
# compiler:
#   # - clang
#   - gcc
# ruby: 2.2.0

cache:
  - directories:
    - $HOME/.cache
addons:
  apt:
    packages: lcov

before_install:
  - chmod +x ./script/*.sh

install:
  - mkdir -p $HOME/.cache
  - touch $HOME/.cache/mydepenency.so
  - ./script/dependencies.sh

script:
  - ./script/build.sh

after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
  # - cat codecov.yml | curl --data-binary @- https://codecov.io/validate
  - codecov
  - bash <(curl -s https://codecov.io/bash) -t 953e6931-a10a-4ef3-8a76-a7b19e82efa9

env:
  global:
    - CODECOV_TOKEN='953e6931-a10a-4ef3-8a76-a7b19e82efa9'

# branches:
#   only:
#     - master
notifications:
  email:
    on_success: change
    on_failure: change
